name: Build and Deploy
env:
  CI: true
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js ðŸ”§
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Update npm ðŸš€
        run: npm install -g npm@latest

      - name: Install and Build ðŸ”§ # Build the Project
        run: |
          npm install
          npm run build

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy on githubio
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          npm run deploy
